### ISSUE TITLE
Some issues with type inference in polymorphic branch

### ISSUE THREAD

**Issue by MatsRooth** [nyusemantics/LambdaCalculator#2]
The file http://conf.ling.cornell.edu/mr249/lambda/bool1.txt tries out polymorphism on binary Boolean type raising.  The first case of raising a ttt conjunction to (et)(et)(et) works.  In the later cases, the type is not inferred at a node where the lambda term is correct.  Here's one case, raising the ttt conjuction to ((et)t)((et)t)((et)t).
![bool1](https://f.cloud.github.com/assets/4483867/1808828/96f46066-6d7e-11e3-987f-dd0bec65d622.png)

I'm not sure though whether what I did accords with the design of the polymorphic type system.

**Comment by MatsRooth** [comment]
I updated the file http://conf.ling.cornell.edu/mr249/lambda/bool1.txt to the current notation for polymorphic types, and it's running with a build from Jan 23 2015. The issues seem to be the same.

**Comment by aualsop** [comment]
This issue is fixed on the current version (Mac/Linux 2.2.0 and Windows 2.1.0).
