### ISSUE TITLE
Reload: if user has unsaved work, add dialog box asking "Are you sure?"

### ISSUE THREAD

**Issue by champoll** [nyusemantics/LambdaCalculator#30]
Currently, when clicking "Reload" after solving a few exercises in a file, the file is immediately reloaded and reset, erasing any progress. It would be good to add a dialog box asking some version of "Are you sure? Unsaved work will be lost". A checkbox "Ask next time" should be added so the user can leave it checked or uncheck it as needed.

**Comment by RTKno1** [comment]
Function added in new update.
